export const STRINGS = {
    enrekangkab: {
        title: "Desa Emas",
        kabkota: 'Kabupaten Enrekang',
        slogan: "Tana Rigalla' Tana Riabussungi",
        logo_kab_url: "https://digitaldesa.id/uploads/logo-desa/enrekang.png",
        logo_dss_url: "https://online.digitaldesa.id/templates/homepage/img/logo_desa_emas_enrekang.svg",
        bg_jumbotron: "https://emonev.afila.co.id/assets/media/login/frame_login_ilustrasi.png",
        nama_user: "Muslimin Bando",
        jabatan_user: "Bupati Enrekang",
        foto_profil: "https://mitrasulawesi.id/wp-content/uploads/2022/10/IMG_20221014_232402.jpg",
        logo_hide: "",
        logo_first: "gap",
        background_color: "#3B2D64",
        font_color: "#ffffff",
        bg_color_jumbotron: "#642ee2",
        font_color_jumbotron: "#ffffff",
    },
    gowakab: {
        title: "Digital Desa",
        kabkota: 'Kabupaten Gowa',
        slogan: "Rewako Gowa",
        logo_kab_url: "https://digitaldesa.id/uploads/logo-desa/gowakab.png",
        logo_dss_url: "",
        bg_jumbotron: "https://i.postimg.cc/LsCDPD71/52432252-2495649517173148-2147568847266250752-n.jpg",
        nama_user: "Adnan Purichta Ichsan",
        jabatan_user: "Bupati Gowa",
        foto_profil: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Bupati_Gowa_Adnan_Purichta_Ichsan.jpg/480px-Bupati_Gowa_Adnan_Purichta_Ichsan.jpg",
        logo_hide: "hide",
        logo_first: "",
        background_color: "#B1DE21",
        font_color: "#202020",
        bg_color_jumbotron: "#C3DE6D",
        font_color_jumbotron: "#202020",
    },
    wajokab: {
        title: "Digital Desa",
        kabkota: 'Kabupaten Wajo',
        slogan: "Maradeka Towajoe Ade'na Napopuang",
        logo_kab_url: "https://digitaldesa.id/uploads/logo-desa/wajokab.png",
        logo_dss_url: "",
        bg_jumbotron: "https://i.postimg.cc/ry3J88nM/Pasangan-Pammase-removebg-preview.png",
        nama_user: "Amran Mahmud",
        jabatan_user: "Bupati Wajo",
        foto_profil: "https://wajokab.go.id/asset/foto_bupati/bupati_amran_mahmud.jpg",
        logo_hide: "hide",
        logo_first: "",
        background_color: "#EF051E",
        font_color: "#ffffff",
        bg_color_jumbotron: "#F05363",
        font_color_jumbotron: "#ffffff",
    },
}
