export const STRINGS = {
    enrekangkab: {
        title: "SI MAWAR KEMBANG DESA",
        desc: "Sistem Informasi Monitoring Pengawasan Administrasi dan Kinerja Pembangunan Desa",
        nama: "Desa Emas",
        kabkota: 'Kabupaten Enrekang',
        slogan: "Tana Rigalla' Tana Riabussungi",
        logo_kab_url: "https://digitaldesa.id/uploads/logo-desa/enrekang.png",
        logo_dss_url: "https://online.digitaldesa.id/templates/homepage/img/logo_desa_emas_enrekang.svg",
        bg_jumbotron: "https://emonev.afila.co.id/assets/media/login/frame_login_ilustrasi.png",
        nama_user: "Muslimin Bando",
        jabatan_user: "Bupati Enrekang",
        foto_profil: "https://mitrasulawesi.id/wp-content/uploads/2022/10/IMG_20221014_232402.jpg",
        logo_hide: "",
        logo_first: "gap",
        background_color: "#3B2D64",
        font_color: "#ffffff",
        bg_color_jumbotron: "#642ee2",
        font_color_jumbotron: "#ffffff",
        logo_second_size: "enrekang",
    },
    gowakab: {
        title: "PENDEKAR",
        desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
        nama: "PENDEKAR",
        kabkota: 'Kabupaten Gowa',
        slogan: "Rewako Gowa",
        logo_kab_url: "https://digitaldesa.id/uploads/logo-desa/gowakab.png",
        logo_dss_url: "",
        bg_jumbotron: "https://i.postimg.cc/fWFtzVwG/photo-2023-07-23-06-36-21.jpg",
        nama_user: "Adnan Purichta Ichsan",
        jabatan_user: "Bupati Gowa",
        foto_profil: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Bupati_Gowa_Adnan_Purichta_Ichsan.jpg/480px-Bupati_Gowa_Adnan_Purichta_Ichsan.jpg",
        logo_hide: "hide",
        logo_first: "",
        background_color: "#327A6E",
        font_color: "#ffffff",
        bg_color_jumbotron: "#92D1C6",
        font_color_jumbotron: "#202020",
        logo_second_size: "",
    },
    wajokab: {
        title: "PENDEKAR",
        desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
        nama: "Mabello",
        kabkota: 'Kabupaten Wajo',
        slogan: "Maradeka Towajoe Ade'na Napopuang",
        logo_kab_url: "https://digitaldesa.id/uploads/logo-desa/wajokab.png",
        logo_dss_url: "https://i.postimg.cc/XYfS3Cfp/Logo-Mabello1-removebg-preview.png",
        bg_jumbotron: "https://i.postimg.cc/ydKPFDt3/5-removebg-preview-removebg-preview.png",
        nama_user: "Amran Mahmud",
        jabatan_user: "Bupati Wajo",
        foto_profil: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Bupati_Gowa_Adnan_Purichta_Ichsan.jpg/480px-Bupati_Gowa_Adnan_Purichta_Ichsan.jpg",
        logo_hide: "",
        logo_first: "gap",
        background_color: "#EF0017",
        font_color: "#ffffff",
        bg_color_jumbotron: "#F03043",
        font_color_jumbotron: "#ffffff",
        logo_second_size: "",
    },
}
