import Enrekang from "../../src/assets/bg/enrekangkab.png";
import Luwu from "../../src/assets/bg/luwukab.jpg";
import Gowa from "../../src/assets/bg/gowakab.jpg";
import Wajo from "../../src/assets/bg/wajokab.jpg";
import Mamasa from "../../src/assets/bg/mamasakab.jpg";
import bupatiEnrekang from "../../src/assets/profil/bupati_enrekang.jpg";
import bupatiLuwu from "../../src/assets/profil/bupati_luwu.jpg";
import bupatiGowa from "../../src/assets/profil/bupati_gowa.jpg";
import bupatiWajo from "../../src/assets/profil/bupati_wajo.jpg";
import bupatiMamasa from "../../src/assets/profil/bupati_mamasa.jpg";
import bupatiKonawe from "../../src/assets/profil/bupati_konawe.jpg";

export const STRINGS = {
  enrekangkab: {
    title: "SI MAWAR KEMBANG DESA",
    desc: "Sistem Informasi Monitoring Pengawasan Administrasi dan Kinerja Pembangunan Desa",
    nama: "Desa Emas",
    kabkota: "Kabupaten Enrekang",
    slogan: "Tana Rigalla' Tana Riabussungi",
    logo_kab_url: "https://digitaldesa.id/uploads/logo-desa/enrekang.png",
    logo_dss_url:
      "https://online.digitaldesa.id/templates/homepage/img/logo_desa_emas_enrekang.svg",
    bg_jumbotron: Enrekang,
    nama_user: "Muslimin Bando",
    jabatan_user: "Bupati Enrekang",
    foto_profil: bupatiEnrekang,
    logo_hide: "",
    logo_first: "gap",
    background_color: "#3B2D64",
    font_color: "#ffffff",
    bg_color_jumbotron: "#642ee2",
    font_color_jumbotron: "#ffffff",
    logo_second_size: "enrekang",
    menu_pelayanan: "hide",
    theme: "",
    alternative_style: "assets/css/style.css",
  },
  luwukab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kabupaten Luwu",
    slogan:
      "Luwu Wanua Mappatuo'e Naewai Alena, Toddo Puli Temmalara Te'bakke Tongengnge",
    logo_kab_url: "https://digitaldesa.id/uploads/logo-desa/luwu.png",
    logo_dss_url: "",
    bg_jumbotron: Luwu,
    nama_user: "Basmin Mattayang",
    jabatan_user: "Bupati Luwu",
    foto_profil: bupatiLuwu,
    logo_hide: "hide",
    logo_first: "",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    logo_second_size: "",
    menu_pelayanan: "hide",
    theme: "",
    alternative_style: "assets/css/alternative-style.css",
  },
  mamasakab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kabupaten Mamasa",
    slogan: "Mesa Kada Dipotuo, Pantan Kada Dipomate",
    logo_kab_url: "https://digitaldesa.id/uploads/logo-desa/mamasakab.png",
    logo_dss_url: "",
    bg_jumbotron: Mamasa,
    nama_user: "Ramlan Badawi",
    jabatan_user: "Bupati Mamasa",
    foto_profil: bupatiMamasa,
    logo_hide: "hide",
    logo_first: "",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    logo_second_size: "",
    menu_pelayanan: "",
    theme: "",
    alternative_style: "assets/css/alternative-style.css",
  },
  gowakab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kabupaten Gowa",
    slogan: "Butta Patturioloang",
    logo_kab_url: "https://digitaldesa.id/uploads/logo-desa/gowakab.png",
    logo_dss_url: "",
    bg_jumbotron: Gowa,
    nama_user: "Adnan Purichta Ichsan",
    jabatan_user: "Bupati Gowa",
    foto_profil: bupatiGowa,
    logo_hide: "hide",
    logo_first: "",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    logo_second_size: "",
    menu_pelayanan: "hide",
    theme: "",
    alternative_style: "assets/css/alternative-style.css",
  },
  wajokab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "Mabello",
    kabkota: "Kabupaten Wajo",
    slogan: "Maradeka Towajoe Ade'na Napopuang",
    logo_kab_url: "https://digitaldesa.id/uploads/logo-desa/wajokab.png",
    logo_dss_url:
      "https://i.postimg.cc/XYfS3Cfp/Logo-Mabello1-removebg-preview.png",
    bg_jumbotron: Wajo,
    nama_user: "Amran Mahmud",
    jabatan_user: "Bupati Wajo",
    foto_profil: bupatiWajo,
    logo_hide: "",
    logo_first: "gap",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    logo_second_size: "",
    menu_pelayanan: "hide",
    theme: "alternative",
    alternative_style: "assets/css/alternative-style.css",
  },
  konawekab: {
    title: "SIMONI ADIK BANGDES",
    desc: "Sistem Informasi Monitoring Administrasi Kinerja Pembangunan Desa",
    nama: "PENDEKAR",
    kabkota: "Kabupaten Konawe",
    slogan: "Wawonii Bangkit",
    logo_kab_url: "https://konawekab.go.id/assets/more_images/logo_besar.png",
    logo_dss_url: "",
    bg_jumbotron: Wajo,
    nama_user: "Harmin Ramba",
    jabatan_user: "Pj. Bupati Konawe",
    foto_profil: bupatiKonawe,
    logo_hide: "hide",
    logo_first: "",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    logo_second_size: "",
    menu_pelayanan: "hide",
    theme: "alternative",
    alternative_style: "assets/css/alternative-style.css",
  },
};
